import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className}`}>
        <Header />
        <main className="mt-[4rem]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
